### ISSUE TITLE
Dependency to mongoose 1.0.0

### ISSUE THREAD

**Issue by gitfy** [bnoguchi/mongoose-types#1]
Hi,
Currently mongoose is on release 0.0.5, but types are dependent on 1.0.0 and registered in npm registry. How can we use this ?

**Comment by bnoguchi** [comment]
```
git clone git://github.com/bnoguchi/mongoose.git
cd mongoose
git checkout bno
npm install
```

This will get you the most up-to-date 1.0 ver of mongoose.

Then just npm install mongoose-types.
