### ISSUE TITLE
More comprehensive email regex

### ISSUE THREAD

**Issue by freewil** [bnoguchi/mongoose-types#2]
Might want to look at http://bassistance.de/jquery-plugins/jquery-plugin-validation/ for a more comprehensive email regex. More specifically here: http://ajax.aspnetcdn.com/ajax/jquery.validate/1.8/jquery.validate.js search for "email:"

**Comment by kazuyukitanimura** [comment]
Not sure if you still need this but I took the regexp from jquery-validation. Check out my repo
https://github.com/kazuyukitanimura/mongoose-types/tree/master/lib/types
